# require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'examples/**'

# BEGIN
require: rubocop-rails

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
# END
